### ISSUE TITLE
Running the demo code did not get the correct results

### ISSUE THREAD

**Issue by chunfenghuayumm** [samuelzhouhe/poseGuidedImgGeneration#4]
Hi！
The result from the pre training model is incorrect, and the finalout picture looks the same as g1out.
Can u help me to solve this problem?
BTW,can I use my own image to generation new pose image?
Thanks a lot

**Comment by samuelzhouhe** [comment]
1. Hi, in our implementation the G2 was able to bring some improvement on the generated image, but the difference might not be very salient, which results in that the final image looks like g1out. Due to time limitations we did not tune G2 to an optimal, and your are more than welcome to play with the hyperparameters or the architecture described in the original paper to make it better.

2. Yes. We did not provide a script for this, but this can be easily done by doing a sess.run on the g2_out tensor with your own image as conditional image in the feed_dict.

**Comment by chunfenghuayumm** [comment]
Hi,thank you for your help.I tried to change parameters to train and found the result was still very bad.
I only  changed LAMBDA.I tried 0.5 and 25, and the results still looks like g1out. Do I need to adjust other parameters instead of just adjusting this parameter of LAMBDA?
      



------------------ 原始邮件 ------------------
发件人: "Samuel He"<notifications@github.com>;
发送时间: 2018年5月8日(星期二) 下午2:46
收件人: "samuelzhouhe/poseGuidedImgGeneration"<poseGuidedImgGeneration@noreply.github.com>;
抄送: "Times`"<664971961@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [samuelzhouhe/poseGuidedImgGeneration] Running the demo code didnot get the correct results (#4)



 
 
Hi, in our implementation the G2 was able to bring some improvement on the generated image, but the difference might not be very salient, which results in that the final image looks like g1out. Due to time limitations we did not tune G2 to an optimal, and your are more than welcome to play with the hyperparameters or the architecture described in the original paper to make it better.
 
 
 
Yes. We did not provide a script for this, but this can be easily done by doing a sess.run on the g2_out tensor with your own image as conditional image in the feed_dict.
